openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts APP
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Contacts APP
tags:
  - name: Contacts
    description: Operations about users.
servers:
  # замінити посилання
  - url: https://nodejs-hw-mongodb-7-oin4.onrender.com
  - url: http://localhost:3000

paths:
  /api/stories:
    get:
      $ref: ../swagger/paths/stories/get.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
