openapi: 3.1.0
info:
  version: 1.0.0
  title: travelers APP
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of travelers APP
tags:
  - name: Contacts
    description: Operations about users.
servers:
  # замінити посилання
  - url: https://nodejs-hw-mongodb-7-oin4.onrender.com
  - url: http://localhost:3000

paths:
  /api/auth/register:
    post:
      $ref: ../swagger\paths\auth\register.yaml
  /api/auth/login:
    post:
      $ref: ../swagger\paths\auth\login.yaml
  /api/auth/refresh:
    post:
      $ref: ../swagger\paths\auth\refresh.yaml
  /api/auth/logout:
    post:
      $ref: ../swagger\paths\auth\logout.yaml

  /api/stories:
    get:
      $ref: ../swagger/paths/stories/get.yaml
  /api/stories/{storyId}:
    patch:
      $ref: ../swagger\paths\stories\{storyId}\patch.yaml
  /api/users:
    get:
      $ref: ../swagger\paths\users\get.yaml
  /api/users/{id}:
    get:
      $ref: ../swagger\paths\users\{userId}\get.yaml
  /api/users/current:
    get:
      $ref: ../swagger\paths\users\current\get.yaml
    patch:
      $ref: ../swagger\paths\users\current\patch.yaml
  /api/users/saved:
    post:
      $ref: ../swagger/paths/users/saved-stories-post.yaml
  /api/users/avatar:
    patch:
      $ref: ../swagger/paths/users/update-avatar.yaml

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: accessToken
