openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts APP
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Contacts APP
tags:
  - name: Contacts
    description: Operations about users.
servers:
  - url: https://nodejs-hw-mongodb-7-oin4.onrender.com
  - url: http://127.0.0.1:8080

paths:
  /contact:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'

  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
