openapi: 3.1.0
info:
  version: 1.0.0
  title: Travelers APP
  description: This is a documentation of the Travelers APP API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
  - name: Auth
    description: Authentication and session management.
  - name: Users
    description: Operations about users (profiles, saved stories, avatars, etc.).
  - name: Stories
    description: Operations related to stories.

servers:
  # замінити посилання
  - url: https://nodejs-hw-mongodb-7-oin4.onrender.com
  - url: http://localhost:3000

paths:
  /api/stories:
    get:
      $ref: ../swagger/paths/stories/get.yaml

  /api/stories/{storyId}:
    patch:
      $ref: ../swagger/paths/stories/{storyId}/patch.yaml

  /api/users/avatar:
    patch:
      $ref: ../swagger/paths/users/update-avatar.yaml

  /api/users/remove:
    patch:
      $ref: ../swagger/paths/users/remove-stories-patch.yaml

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: accessToken